name: PPOIS CI/CD Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./lab1

    steps:
    - name: 1. Скачивание кода репозитория
      uses: actions/checkout@v4

    - name: 2. Настройка окружения Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: 3. Установка необходимых библиотек
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage pyinstaller

    - name: 4. Проверка качества кода (Linter)
      run: |
        flake8 . --count --max-line-length=150 --show-source --statistics

    - name: 5. Запуск unit-тестов и проверка покрытия
      run: |
        # Указываем новый путь к тестам словаря
        coverage run -m unittest dictionary/test_dictionary.py
        coverage report -m

    - name: 6. Сборка независимого исполняемого файла
      run: |
        # Указываем новый путь к main.py словаря
        pyinstaller --onefile dictionary/main.py

    - name: 7. Сохранение артефакта сборки
      uses: actions/upload-artifact@v4
      with:
        name: dictionary-app-linux
        path: lab1/dist/main